// Generated by CoffeeScript 1.12.5
(function() {
  $.extend($.summernote.options, {
    sEmoji: {
      icon: '<span class="note-current-emoji">😀</span> ',
      tooltip: 'Insert Emoji',
      list: ['😀', '😃', '😂', '😊', '😉', '😋', '😎', '🙁', '😡', '😐', '😲', '😱', '😴', '🙄 ', '😈']
    }
  });

  $.extend($.summernote.plugins, {
    'sEmoji': function(context) {
      var options, sEmojiOptions, ui;
      ui = $.summernote.ui;
      options = context.options;
      sEmojiOptions = options.sEmoji;
      return context.memo('button.sEmoji', function() {
        var emojiButton;
        emojiButton = ui.buttonGroup([
          ui.button({
            className: 'dropdown-toggle',
            contents: sEmojiOptions.icon + ui.icon(options.icons.caret, 'span'),
            tooltip: sEmojiOptions.tooltip
          }, {
            data: {
              toggle: 'dropdown'
            }
          }), ui.dropdownCheck({
            className: 'dropdown-emoji',
            items: sEmojiOptions.list,
            template: function(item) {
              return item;
            },
            callback: function($dropdown) {
              return $dropdown.find('a').each(function() {
                $(this).on('click', function(e) {
                  e.preventDefault();
                  context.invoke('editor.restoreRange');
                  context.invoke('editor.focus');
                  context.invoke('editor.insertText', this.textContent);
                  return false;
                });
              });
            }
          })
        ]);
        return emojiButton.render();
      });
    }
  });

}).call(this);
